/**
 * Post-build script: injects per-route title, description, canonical, OG/Twitter
 * meta tags and JSON-LD schema into the static HTML files generated by vite-react-ssg.
 *
 * Run automatically after `vite-react-ssg build` via the npm build script.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "fs";
import { join, relative } from "path";

const BASE = "https://thatworksco.com";
const OG_IMG = `${BASE}/logo.svg`;
const DIST = join(process.cwd(), "dist");

// ─── Static route meta ────────────────────────────────────────────────────────

const STATIC_META = {
  "/": {
    title: "High Performance GTM Systems for B2B — That Works",
    description:
      "We design and implement full-funnel marketing infrastructure for B2B companies. Strategy, infrastructure, execution — designed, implemented, yours forever.",
    jsonLd: [
      {
        "@context": "https://schema.org",
        "@type": "ItemList",
        itemListElement: [
          { "@type": "Service", position: 1, provider: { "@type": "Organization", name: "That Works" }, name: "Brand System & Positioning", description: "We build the whole brand system — identity, positioning, voice and a full message bank — and hand it over.", url: `${BASE}/services/branding` },
          { "@type": "Service", position: 2, provider: { "@type": "Organization", name: "That Works" }, name: "Inbound Marketing Infrastructure", description: "An inbound system that attracts the right buyers, captures them, and moves them toward a conversation.", url: `${BASE}/services/inbound` },
          { "@type": "Service", position: 3, provider: { "@type": "Organization", name: "That Works" }, name: "B2B Lead Generation System", description: "A custom-built lead generation engine that scrapes, enriches, researches and delivers fully personalised outreach at scale.", url: `${BASE}/services/lead-gen` },
          { "@type": "Service", position: 4, provider: { "@type": "Organization", name: "That Works" }, name: "Customer Retention System", description: "Systems that keep customers engaged, equip your sales team to close, and turn happy customers into your best growth channel.", url: `${BASE}/services/retention` },
        ],
      },
      {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: [
          { "@type": "Question", name: "What does That Works do?", acceptedAnswer: { "@type": "Answer", text: "That Works builds full-funnel GTM and lead generation systems for B2B companies — designed, implemented, and handed over to you." } },
          { "@type": "Question", name: "Who is That Works for?", acceptedAnswer: { "@type": "Answer", text: "We work with B2B companies from 0 to 1 through to scale — typically founders and marketing leads who need systems, not just strategy." } },
          { "@type": "Question", name: "How do I get started?", acceptedAnswer: { "@type": "Answer", text: "Book a 20-minute diagnostic call at thatworksco.com. We'll figure out where you are and what you need." } },
        ],
      },
    ],
  },
  "/approach": {
    title: "How It Works — Strategy, Infrastructure & Handover — That Works",
    description: "Strategy. Infrastructure. Execution. Handed over. We take care of the whole thing and leave you with a marketing function that runs without us.",
    jsonLd: { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "How It Works", item: `${BASE}/approach` }] },
  },
  "/about": {
    title: "About — That Works",
    description: "Learn about That Works — the team behind high performance GTM systems for B2B companies. Strategy, infrastructure, execution and handover.",
    jsonLd: { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "About", item: `${BASE}/about` }] },
  },
  "/contact": {
    title: "Contact — That Works",
    description: "Get in touch with That Works. We design and implement high performance GTM systems for B2B companies. Let's talk about what you need.",
    jsonLd: { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Contact", item: `${BASE}/contact` }] },
  },
  "/services": {
    title: "GTM Services — Find Your Entry Point — That Works",
    description: "Two ways in. One outcome: a marketing function that runs without us. Choose Marketing OS for your growth stage, or a standalone specialist service.",
    jsonLd: { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Services", item: `${BASE}/services` }] },
  },
  "/services/lead-gen": {
    title: "B2B Lead Generation Systems — That Works",
    description: "A custom-built lead generation engine that scrapes, enriches, researches and delivers fully personalised outreach at scale, without your team lifting a finger.",
    jsonLd: [
      { "@context": "https://schema.org", "@type": "Service", name: "B2B Lead Generation System", serviceType: "Lead Generation", provider: { "@type": "Organization", name: "That Works", url: BASE }, description: "A custom-built lead generation engine that scrapes, enriches, researches and delivers fully personalised outreach at scale.", url: `${BASE}/services/lead-gen` },
      { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Services", item: `${BASE}/services` }, { "@type": "ListItem", position: 3, name: "Lead Generation", item: `${BASE}/services/lead-gen` }] },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
        { "@type": "Question", name: "We've never done structured outbound before. Where do we even start?", acceptedAnswer: { "@type": "Answer", text: "That's exactly the situation we're built for. We start with your ICP — who you're actually selling to — and build everything from there. By the time we hand over, you have a defined target list, working sequences, a configured CRM pipeline, and a prospecting SOP your team can run without us." } },
        { "@type": "Question", name: "What tools do you use, and do we own them?", acceptedAnswer: { "@type": "Answer", text: "We design the stack around your situation. At minimum: a CRM (HubSpot, Pipedrive, or similar), an email sequencing tool (Instantly, Lemlist, or similar), a prospecting data source (Apollo, Clay, or similar), and custom-built automation workflows connecting them. Every tool is set up in your name, paid by you, owned by you." } },
        { "@type": "Question", name: "How long before outbound starts generating pipeline?", acceptedAnswer: { "@type": "Answer", text: "The build takes 2–4 weeks. Realistic first results — replies, booked meetings — typically appear within 2–6 weeks of the system going live. We build for consistency, not quick wins that burn your domain reputation." } },
        { "@type": "Question", name: "We've tried cold email before and got blacklisted. How do you avoid that?", acceptedAnswer: { "@type": "Answer", text: "Domain health, sending limits, warm-up protocol, and copy that doesn't trigger spam filters — all built into the infrastructure from day one, not bolted on after something breaks. Most blacklisting happens because people skip setup. We don't." } },
        { "@type": "Question", name: "How do you define who we should be targeting?", acceptedAnswer: { "@type": "Answer", text: "ICP definition is the first thing we do — before any outreach is built. We validate against your existing customers, your market, and your positioning. A system built on a vague ICP produces vague results. Most outbound failures are an ICP problem, not a copy problem." } },
      ] },
    ],
  },
  "/services/inbound": {
    title: "Inbound Marketing Infrastructure — That Works",
    description: "The best leads find you. We build inbound as infrastructure — a system that attracts the right buyers, captures them, and moves them toward a conversation.",
    jsonLd: [
      { "@context": "https://schema.org", "@type": "Service", name: "Inbound Marketing Infrastructure", serviceType: "Inbound Marketing", provider: { "@type": "Organization", name: "That Works", url: BASE }, description: "An inbound system that attracts the right buyers, captures them, and moves them toward a conversation without your team having to chase.", url: `${BASE}/services/inbound` },
      { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Services", item: `${BASE}/services` }, { "@type": "ListItem", position: 3, name: "Inbound Marketing", item: `${BASE}/services/inbound` }] },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
        { "@type": "Question", name: "What does an inbound marketing system actually include?", acceptedAnswer: { "@type": "Answer", text: "It's not just a blog. An inbound system includes a documented content strategy, channel selection and rationale, an SEO foundation, a content calendar, distribution SOPs, and the workflows that make it repeatable without depending on one person's time." } },
        { "@type": "Question", name: "How is this different from just hiring a content writer?", acceptedAnswer: { "@type": "Answer", text: "A content writer executes. We build the system that tells them what to write, where to publish it, how to distribute it, and how to measure whether it's working. Without the system underneath, a great writer produces content that goes nowhere." } },
        { "@type": "Question", name: "Which channels do you build for?", acceptedAnswer: { "@type": "Answer", text: "We start with your ICP and work backwards. For most B2B businesses at your stage, that means LinkedIn first, supported by a content hub for SEO, and optionally a newsletter for list-building. We never build more channels than your team can actually run." } },
        { "@type": "Question", name: "How long before inbound starts generating leads?", acceptedAnswer: { "@type": "Answer", text: "Inbound compounds over time, not overnight. Most clients see meaningful traction within 3–6 months of a properly built system going live. The build takes 4–8 weeks. We set expectations clearly at the start so you're not measuring the wrong thing at the wrong time." } },
        { "@type": "Question", name: "Do you create the content or just the system?", acceptedAnswer: { "@type": "Answer", text: "Both. We build the system and seed it — strategy documented, first content calendar built, templates created, and in most tiers we produce the first batch of content to demonstrate the standard. After handover, your team runs it with everything they need." } },
      ] },
    ],
  },
  "/services/branding": {
    title: "Brand System & Positioning — That Works",
    description: "Your brand. Built to last. We build the whole brand system — identity, positioning, voice and a full message bank — and hand it over so it runs without us.",
    jsonLd: [
      { "@context": "https://schema.org", "@type": "Service", name: "Brand System & Positioning", serviceType: "Branding", provider: { "@type": "Organization", name: "That Works", url: BASE }, description: "We build the whole brand system — identity, positioning, voice and a full message bank — handed over to you.", url: `${BASE}/services/branding` },
      { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Services", item: `${BASE}/services` }, { "@type": "ListItem", position: 3, name: "Branding", item: `${BASE}/services/branding` }] },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
        { "@type": "Question", name: "We already have a logo. Do we still need brand infrastructure?", acceptedAnswer: { "@type": "Answer", text: "A logo is the surface. Brand infrastructure is everything underneath — positioning, messaging, tone of voice, the way you describe what you do and why it matters. Most B2B businesses have a visual identity and no strategic foundation. That's why their marketing feels inconsistent and their sales conversations feel hard." } },
        { "@type": "Question", name: "How does brand work connect to pipeline? We need leads, not aesthetics.", acceptedAnswer: { "@type": "Answer", text: "Brand is what makes every other channel work harder. Clear positioning shortens sales cycles. A strong message makes cold outreach land better. Consistent tone makes content more recognisable. The businesses that scale fastest aren't the ones with the best ads — they're the ones with the clearest story." } },
        { "@type": "Question", name: "What do we actually receive as brand deliverables?", acceptedAnswer: { "@type": "Answer", text: "A positioning document, a full messaging framework with pillars and proof points, a tone of voice guide with examples, core content templates, and a visual direction brief for your designer. Everything is documented, handed over, and built to be used — not filed and forgotten." } },
        { "@type": "Question", name: "Our founder is the brand right now. How do we systematise that?", acceptedAnswer: { "@type": "Answer", text: "This is one of the most common situations we work with. Founder-led brand is powerful — but it only scales if you extract the thinking behind it into a documented system. We do that: positioning, messaging pillars, tone of voice, and content templates that let anyone on your team communicate with the same clarity and energy as the founder." } },
        { "@type": "Question", name: "How do you make sure the brand stays consistent after you hand it over?", acceptedAnswer: { "@type": "Answer", text: "Consistency comes from documentation, not supervision. Every brand engagement ends with a tone of voice guide, messaging framework, and content templates your team can use independently. We train whoever needs to use it before we leave." } },
      ] },
    ],
  },
  "/services/retention": {
    title: "Customer Retention Systems — That Works",
    description: "Acquisition gets the credit. Retention builds the business. We design the systems that keep customers engaged, equip your sales team to close, and drive net revenue retention.",
    jsonLd: [
      { "@context": "https://schema.org", "@type": "Service", name: "Customer Retention System", serviceType: "Retention Marketing", provider: { "@type": "Organization", name: "That Works", url: BASE }, description: "Systems that keep customers engaged, equip your sales team to close, and turn happy customers into your best growth channel.", url: `${BASE}/services/retention` },
      { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Services", item: `${BASE}/services` }, { "@type": "ListItem", position: 3, name: "Retention", item: `${BASE}/services/retention` }] },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
        { "@type": "Question", name: "We're focused on acquiring new customers — why should we invest in retention now?", acceptedAnswer: { "@type": "Answer", text: "Because every customer you lose makes acquisition more expensive. If your retention rate is poor, you're filling a leaky bucket — every pound you spend on growth is partially funding churn. Fixing retention at the system level is almost always a higher ROI investment than spending more on acquisition, and most businesses leave it too late." } },
        { "@type": "Question", name: "What does a retention marketing system actually look like?", acceptedAnswer: { "@type": "Answer", text: "It's the infrastructure that keeps customers engaged, informed, and expanding after they've signed. That includes onboarding sequences, lifecycle email flows, adoption touchpoints, renewal and expansion triggers, NPS feedback loops, and the reporting that tells you where customers are dropping off before they churn." } },
        { "@type": "Question", name: "How do you reduce churn without just adding more touchpoints?", acceptedAnswer: { "@type": "Answer", text: "More touchpoints without better signals is just noise. We start by identifying where in the customer journey churn is actually happening — then build interventions that address the real cause. Sometimes that's an onboarding gap. Sometimes it's a product adoption problem. The system targets the root cause, not the symptom." } },
        { "@type": "Question", name: "How do you measure whether retention is working?", acceptedAnswer: { "@type": "Answer", text: "The primary metrics are net revenue retention (NRR), churn rate, and expansion revenue. Below those, you're tracking product or service adoption rates, NPS trends, and engagement signals in your lifecycle flows. We build the reporting dashboard into the retention system so you always know where you stand." } },
        { "@type": "Question", name: "At what stage does it make sense to build a retention system?", acceptedAnswer: { "@type": "Answer", text: "As soon as you have customers worth keeping — which for most B2B businesses is earlier than they think. If you have 10+ active clients and no systematic way of measuring their health, engaging them, or identifying expansion opportunities, you already need this." } },
      ] },
    ],
  },
  "/services/marketing-os/zero-to-one": {
    title: "Marketing OS: Zero to One — Build Your First GTM Engine — That Works",
    description: "Building your first marketing engine. ICP, positioning, CRM setup and a 90-day roadmap — built for founders with a product ready to sell but zero marketing infrastructure.",
    jsonLd: [
      { "@context": "https://schema.org", "@type": "Service", name: "Marketing OS: Zero to One", serviceType: "GTM System Build", provider: { "@type": "Organization", name: "That Works", url: BASE }, description: "Building your first marketing engine from scratch — ICP, positioning, CRM setup, and a 90-day roadmap.", url: `${BASE}/services/marketing-os/zero-to-one` },
      { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Services", item: `${BASE}/services` }, { "@type": "ListItem", position: 3, name: "Marketing OS: Zero to One", item: `${BASE}/services/marketing-os/zero-to-one` }] },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
        { "@type": "Question", name: "What do we actually own at the end of the engagement?", acceptedAnswer: { "@type": "Answer", text: "Everything. Every document, SOP, playbook, tool setup, and strategy is yours. We don't retain access, we don't lock anything behind a retainer, and you don't need us to run what we've built." } },
        { "@type": "Question", name: "How is That Works different from hiring a fractional CMO?", acceptedAnswer: { "@type": "Answer", text: "A fractional CMO advises. We build. You get a complete, documented marketing system — tools configured, processes written, team trained — not strategic guidance that leaves the moment the contract ends." } },
        { "@type": "Question", name: "Do you work with us ongoing, or is this a one-time engagement?", acceptedAnswer: { "@type": "Answer", text: "The engagement has a defined end. We're not selling a retainer — we're selling a build. There's an optional Engine Tune-Up retainer for strategic oversight after the engagement closes, but that's your choice, not ours." } },
        { "@type": "Question", name: "What does the handover process look like?", acceptedAnswer: { "@type": "Answer", text: "The final week of every engagement is dedicated to handover — a working session with your team, full documentation walkthrough, and a 30-day check-in after we're done." } },
        { "@type": "Question", name: "Everything is in my head and nothing is written down. Is that too early for this?", acceptedAnswer: { "@type": "Answer", text: "It's the perfect time. The 0→1 stage is exactly where we do our best work — extracting what's in your head, turning it into a documented strategy, and building the first systems before bad habits get entrenched. Waiting until you're bigger doesn't make the foundation easier to build. It makes it harder." } },
        { "@type": "Question", name: "We're 100% founder-led right now. Can this work without a marketing team?", acceptedAnswer: { "@type": "Answer", text: "Yes — that's the most common situation we work with at this stage. We design the system for your current resource level, which may just be you. The deliverable is a foundation you can hand to your first marketing hire the moment you're ready — so they hit the ground running instead of starting from scratch." } },
      ] },
    ],
  },
  "/services/marketing-os/friction": {
    title: "Marketing OS: Friction — Fix What's Breaking — That Works",
    description: "Marketing spend up, results flat, pipeline unpredictable? We run a full audit, diagnose exactly where the break is, and rebuild from the ground up.",
    jsonLd: [
      { "@context": "https://schema.org", "@type": "Service", name: "Marketing OS: Friction", serviceType: "GTM Audit & Rebuild", provider: { "@type": "Organization", name: "That Works", url: BASE }, description: "Full marketing audit, ICP refinement, attribution framework, and a recovery roadmap for businesses where spend is up but results are flat.", url: `${BASE}/services/marketing-os/friction` },
      { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Services", item: `${BASE}/services` }, { "@type": "ListItem", position: 3, name: "Marketing OS: Friction", item: `${BASE}/services/marketing-os/friction` }] },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
        { "@type": "Question", name: "What do we actually own at the end of the engagement?", acceptedAnswer: { "@type": "Answer", text: "Everything. Every document, SOP, playbook, tool setup, and strategy is yours. We don't retain access, we don't lock anything behind a retainer, and you don't need us to run what we've built." } },
        { "@type": "Question", name: "How is That Works different from hiring a fractional CMO?", acceptedAnswer: { "@type": "Answer", text: "A fractional CMO advises. We build. You get a complete, documented marketing system — tools configured, processes written, team trained — not strategic guidance that leaves the moment the contract ends." } },
        { "@type": "Question", name: "Do you work with us ongoing, or is this a one-time engagement?", acceptedAnswer: { "@type": "Answer", text: "The engagement has a defined end. We're not selling a retainer — we're selling a build. There's an optional Engine Tune-Up retainer for strategic oversight after the engagement closes, but that's your choice, not ours." } },
        { "@type": "Question", name: "What does the handover process look like?", acceptedAnswer: { "@type": "Answer", text: "The final week of every engagement is dedicated to handover — a working session with your team, full documentation walkthrough, and a 30-day check-in after we're done." } },
        { "@type": "Question", name: "We have a team, budget, and activity — but revenue isn't growing. How do you diagnose that?", acceptedAnswer: { "@type": "Answer", text: "The Friction stage almost always points to one of three root causes: the wrong ICP, a broken conversion layer, or activity without a system connecting it to revenue. We start with a full audit — what exists, what's broken, what's missing — before recommending anything. We fix the right thing, not the most visible thing." } },
        { "@type": "Question", name: "We already have tools and processes in place. Do we start again or work with what we have?", acceptedAnswer: { "@type": "Answer", text: "We audit what exists first. If it's working, we keep it. If it's creating friction, we replace it. We never rip out infrastructure for the sake of it — but we also won't leave a broken system in place just because it's familiar. You'll know exactly what stays, what changes, and why before we touch anything." } },
      ] },
    ],
  },
  "/services/marketing-os/scale": {
    title: "Marketing OS: Scale — Systemise for Growth — That Works",
    description: "Your team is stretched thin with no clear priority. We streamline operations, eliminate bottlenecks, and build the systems that turn a busy team into a productive one.",
    jsonLd: [
      { "@context": "https://schema.org", "@type": "Service", name: "Marketing OS: Scale", serviceType: "Marketing Operations & Systems", provider: { "@type": "Organization", name: "That Works", url: BASE }, description: "Operations audit, prioritisation framework, workflow redesign, and a 90-day scaling roadmap for growing businesses.", url: `${BASE}/services/marketing-os/scale` },
      { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Services", item: `${BASE}/services` }, { "@type": "ListItem", position: 3, name: "Marketing OS: Scale", item: `${BASE}/services/marketing-os/scale` }] },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
        { "@type": "Question", name: "What do we actually own at the end of the engagement?", acceptedAnswer: { "@type": "Answer", text: "Everything. Every document, SOP, playbook, tool setup, and strategy is yours. We don't retain access, we don't lock anything behind a retainer, and you don't need us to run what we've built." } },
        { "@type": "Question", name: "How is That Works different from hiring a fractional CMO?", acceptedAnswer: { "@type": "Answer", text: "A fractional CMO advises. We build. You get a complete, documented marketing system — tools configured, processes written, team trained — not strategic guidance that leaves the moment the contract ends." } },
        { "@type": "Question", name: "Do you work with us ongoing, or is this a one-time engagement?", acceptedAnswer: { "@type": "Answer", text: "The engagement has a defined end. We're not selling a retainer — we're selling a build. There's an optional Engine Tune-Up retainer for strategic oversight after the engagement closes, but that's your choice, not ours." } },
        { "@type": "Question", name: "What does the handover process look like?", acceptedAnswer: { "@type": "Answer", text: "The final week of every engagement is dedicated to handover — a working session with your team, full documentation walkthrough, and a 30-day check-in after we're done." } },
        { "@type": "Question", name: "We're moving but every step feels heavier. How do you fix that without slowing us down?", acceptedAnswer: { "@type": "Answer", text: "The weight usually comes from manual processes that haven't been systematised, team members doing work that should be automated, and decisions being made reactively instead of from a clear playbook. We identify the highest-friction points first and build relief there — so the system gets lighter as you grow, not heavier." } },
        { "@type": "Question", name: "We're firefighting constantly. How do we stop without dropping everything?", acceptedAnswer: { "@type": "Answer", text: "Firefighting is a systems problem, not a people problem. We build the SOPs, decision frameworks, and role clarity that let your team handle recurring situations without escalating everything. The goal is a marketing function that runs on process, not on founder availability." } },
      ] },
    ],
  },
  "/services/marketing-os/leader": {
    title: "Marketing OS: Leader — Close the Lifecycle Gaps — That Works",
    description: "Established business with invisible churn or stagnating pipeline? We map your full customer lifecycle, identify exactly where customers drop off, and close the gaps.",
    jsonLd: [
      { "@context": "https://schema.org", "@type": "Service", name: "Marketing OS: Leader", serviceType: "Customer Lifecycle & Retention", provider: { "@type": "Organization", name: "That Works", url: BASE }, description: "Marketing health diagnostic, customer lifecycle mapping, churn risk identification, and a retention recovery roadmap for established businesses.", url: `${BASE}/services/marketing-os/leader` },
      { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Services", item: `${BASE}/services` }, { "@type": "ListItem", position: 3, name: "Marketing OS: Leader", item: `${BASE}/services/marketing-os/leader` }] },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
        { "@type": "Question", name: "What do we actually own at the end of the engagement?", acceptedAnswer: { "@type": "Answer", text: "Everything. Every document, SOP, playbook, tool setup, and strategy is yours. We don't retain access, we don't lock anything behind a retainer, and you don't need us to run what we've built." } },
        { "@type": "Question", name: "How is That Works different from hiring a fractional CMO?", acceptedAnswer: { "@type": "Answer", text: "A fractional CMO advises. We build. You get a complete, documented marketing system — tools configured, processes written, team trained — not strategic guidance that leaves the moment the contract ends." } },
        { "@type": "Question", name: "Do you work with us ongoing, or is this a one-time engagement?", acceptedAnswer: { "@type": "Answer", text: "The engagement has a defined end. We're not selling a retainer — we're selling a build. There's an optional Engine Tune-Up retainer for strategic oversight after the engagement closes, but that's your choice, not ours." } },
        { "@type": "Question", name: "What does the handover process look like?", acceptedAnswer: { "@type": "Answer", text: "The final week of every engagement is dedicated to handover — a working session with your team, full documentation walkthrough, and a 30-day check-in after we're done." } },
        { "@type": "Question", name: "Growth is happening but we can't explain what's driving it. Is that actually a problem?", acceptedAnswer: { "@type": "Answer", text: "Yes — because what you can't explain, you can't protect, replicate, or scale. If your growth is driven by factors you don't understand, you have no way of doubling down on what's working or catching the early signs of what's about to stop. Visibility is infrastructure too." } },
        { "@type": "Question", name: "How do you build a marketing function that doesn't depend on one person to run it?", acceptedAnswer: { "@type": "Answer", text: "By replacing person-dependent knowledge with documented systems. Every process, decision framework, and playbook lives in a place the whole team can access and follow. When the person changes, the system stays. That's what we build — and it's exactly what most growing companies are missing." } },
      ] },
    ],
  },
  "/faq": {
    title: "Frequently Asked Questions — That Works",
    description: "Everything you need to know about That Works — what we do, how the model works, who we're built for, and what to expect from an engagement.",
    jsonLd: [
      { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "FAQ", item: `${BASE}/faq` }] },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
        { "@type": "Question", name: "What does That Works Co actually do?", acceptedAnswer: { "@type": "Answer", text: "We build marketing infrastructure for B2B businesses — the strategy, systems, tools, processes, and playbooks that make a marketing function run properly. We're not an agency managing your ongoing execution. We design and build the engine, then hand it over completely. After the engagement, you own everything and you don't need us to run it." } },
        { "@type": "Question", name: "Who is That Works built for?", acceptedAnswer: { "@type": "Answer", text: "B2B SaaS, professional services, and consultancy businesses that are past product-market fit and into early growth — typically 30 to 200 employees, £500k to £10M ARR, at Seed to Series B. Usually founder-led or with a small marketing team that's under-resourced relative to what the business actually needs." } },
        { "@type": "Question", name: "What's the difference between Marketing OS and Point Solutions?", acceptedAnswer: { "@type": "Answer", text: "Two ways into That Works. Marketing OS is for businesses that know what stage of growth they're at and need the full infrastructure built for that stage. Point Solutions are for businesses that know exactly what gap they need filled — brand, inbound, outbound, or retention — and want that specific system built. Both end with a full handover. Both are one-time builds, not ongoing retainers." } },
        { "@type": "Question", name: "What category does That Works sit in?", acceptedAnswer: { "@type": "Answer", text: "We call it 0→1 Marketing Infrastructure. It's an emerging category that sits between fractional CMO (advisory, no build) and marketing agency (execution, no foundation). We do the foundational work that makes everything else work — and then we leave." } },
        { "@type": "Question", name: "How is That Works different from a marketing agency?", acceptedAnswer: { "@type": "Answer", text: "Agencies optimise for dependency — they need you on retainer to justify their model. We optimise for capability transfer. Our goal is a client who doesn't need us. Every engagement ends with a full handover — the client owns everything we build, and we train their team to run it." } },
        { "@type": "Question", name: "How is That Works different from hiring a fractional CMO?", acceptedAnswer: { "@type": "Answer", text: "A fractional CMO advises. We build. You get a complete, documented marketing system — tools configured, processes written, team trained — not strategic guidance that leaves the moment the contract ends. The output is infrastructure, not insight." } },
        { "@type": "Question", name: "Do you work with us ongoing, or is this a one-time engagement?", acceptedAnswer: { "@type": "Answer", text: "The engagement has a defined end. We're not selling a retainer — we're selling a build. There's an optional Engine Tune-Up retainer for strategic oversight after the engagement closes, but that's your choice, not ours. We design every project to end with you fully capable of running what we've built." } },
        { "@type": "Question", name: "What do we actually own at the end of the engagement?", acceptedAnswer: { "@type": "Answer", text: "Everything. Every document, SOP, playbook, tool setup, and strategy is yours. We don't retain access, we don't lock anything behind a retainer, and you don't need us to run what we've built. It belongs to you the moment we hand it over." } },
        { "@type": "Question", name: "What does the handover process look like?", acceptedAnswer: { "@type": "Answer", text: "The final week of every engagement is dedicated to handover — a working session with your team, full documentation walkthrough, and a 30-day check-in after we're done. You leave knowing how to run everything we've built." } },
        { "@type": "Question", name: "Do we need a marketing team in place before we start?", acceptedAnswer: { "@type": "Answer", text: "No. Most clients come to us with no marketing team, or one junior person. We design the system for your current resource level and build in a hiring brief for when you're ready to scale. The system is designed to be operated by junior people once it's built." } },
        { "@type": "Question", name: "We have a marketing hire already. Can That Works still help?", acceptedAnswer: { "@type": "Answer", text: "Yes — and in most cases, the system we build makes that person dramatically more effective. If you have a junior or mid-level marketer with no senior infrastructure behind them, that's exactly who we build for. They get the strategy, tools, processes, and playbooks to execute at a level above their experience." } },
        { "@type": "Question", name: "How long does an engagement take?", acceptedAnswer: { "@type": "Answer", text: "Depending on scope: the Foundation Sprint (0→1) is 4 weeks. The Engine Build is 8 weeks. The Full OS is 12 weeks. Point Solution builds typically run 4–8 weeks depending on complexity. We set a fixed timeline at the start of every engagement." } },
        { "@type": "Question", name: "How intensive is this for our team during the engagement?", acceptedAnswer: { "@type": "Answer", text: "Two working sessions per week is the primary commitment — for the founder or marketing lead. Outside of those sessions, there's async review of deliverables. We do the heavy lifting. We're designed around the reality that you're still running a business while this is happening." } },
        { "@type": "Question", name: "We already tried an agency and it didn't work. How is this different?", acceptedAnswer: { "@type": "Answer", text: "Agencies optimise for dependency — they need you on retainer to justify their model. We optimise for capability transfer. Our goal is a client who doesn't need us. We build things that outlive us. That's not a line — it's the structural logic of how we work." } },
        { "@type": "Question", name: "What's the real cost of not building this?", acceptedAnswer: { "@type": "Answer", text: "Every month without a marketing foundation is a month of pipeline you can't measure, improve, or replicate. Most of our clients come to us after 6+ months of spending on tactics that didn't compound — ads, freelancers, a hire that didn't work out. The cost isn't just the money. It's the time, the missed quarter, and the investor conversation you weren't ready for." } },
        { "@type": "Question", name: "What tools do you use?", acceptedAnswer: { "@type": "Answer", text: "We design the stack around your situation. Typically: a CRM (HubSpot, Pipedrive, or similar), email sequencing (Instantly, Lemlist, or similar), prospecting data (Apollo, Clay, or similar), content and SEO tooling, and custom-built automation workflows connecting everything. Every tool is set up in your name, paid by you, owned by you." } },
        { "@type": "Question", name: "Do you write content and copy, or just build the system?", acceptedAnswer: { "@type": "Answer", text: "Both, depending on the engagement. We build the system and seed it — the strategy is documented, the first content calendar is built, templates and briefs are created, and in most tiers we produce the first batch of content to demonstrate the standard. After handover, your team runs it." } },
        { "@type": "Question", name: "How do you define who we should be targeting?", acceptedAnswer: { "@type": "Answer", text: "ICP definition is the first thing we do in every engagement — before any system is built. We validate against your existing customers, your market, and your positioning. A system built on a vague ICP produces vague results." } },
        { "@type": "Question", name: "How long before we see results?", acceptedAnswer: { "@type": "Answer", text: "Depends on the channel. Outbound can generate first replies and meetings within 2–6 weeks of go-live. Inbound compounds over 3–6 months. Brand work affects everything downstream over time. We set clear expectations per channel at the start of every engagement." } },
        { "@type": "Question", name: "Can you guarantee results?", acceptedAnswer: { "@type": "Answer", text: "No — and we won't. We deliver the infrastructure, not the results of its use. What we can guarantee is that everything we build is documented, handed over, and built to the standard your team can operate and improve. The results depend on execution, market conditions, and factors outside our control. Anyone who guarantees pipeline numbers is selling you something we're not." } },
        { "@type": "Question", name: "What if we're not ready for a full engagement?", acceptedAnswer: { "@type": "Answer", text: "The Foundation Sprint exists for exactly this situation — 4 weeks, clarity and direction, a documented foundation you can act on immediately. It's also the natural step before a full Engine Build for businesses that want to validate direction before committing to a larger investment." } },
        { "@type": "Question", name: "What stage should we be at to work with you?", acceptedAnswer: { "@type": "Answer", text: "Post product-market fit, with early revenue. We're not the right fit for pre-revenue startups — systems and scale are the wrong investment before you've validated the product. If you're at Seed or Series A with traction and a growing team, you're in the right place." } },
        { "@type": "Question", name: "What if we already have strong opinions about how marketing should work?", acceptedAnswer: { "@type": "Answer", text: "We need the mandate to build — or redesign — meaningfully. If there's a senior marketer who's been doing things their way for years and isn't open to structural change, the engagement will be difficult for both sides. We work best with clients who want the foundation rebuilt properly, not clients who want validation for what they're already doing." } },
        { "@type": "Question", name: "How do we get started?", acceptedAnswer: { "@type": "Answer", text: "Book a discovery call. No pitch, no deck — just a conversation to understand where you are, what's breaking, and whether That Works is the right fit. If it is, we'll tell you which engagement makes sense and what the next step looks like." } },
      ] },
    ],
  },
  "/blog": {
    title: "GTM Insights & Resources — That Works",
    description: "Practical insight on GTM strategy, marketing systems, lead generation, and revenue architecture for B2B companies. Written by practitioners, not theorists.",
    jsonLd: { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Blog", item: `${BASE}/blog` }] },
  },
  "/book-a-call": {
    title: "Book a Diagnostic Call — That Works",
    description: "Book a free 20-minute diagnostic call with That Works. We'll figure out exactly where you are, what's breaking, and what you need to build a marketing function that runs.",
    jsonLd: { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE }, { "@type": "ListItem", position: 2, name: "Book a Call", item: `${BASE}/book-a-call` }] },
  },
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function esc(s) {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function buildHeadTags({ title, description, canonical, noindex, jsonLd }) {
  const jsonLdArray = jsonLd ? (Array.isArray(jsonLd) ? jsonLd : [jsonLd]) : [];
  return [
    `<title>${title}</title>`,
    `<meta name="description" content="${esc(description)}">`,
    noindex ? `<meta name="robots" content="noindex, nofollow">` : null,
    `<link rel="canonical" href="${canonical}">`,
    `<meta property="og:type" content="website">`,
    `<meta property="og:url" content="${canonical}">`,
    `<meta property="og:title" content="${esc(title)}">`,
    `<meta property="og:description" content="${esc(description)}">`,
    `<meta property="og:image" content="${OG_IMG}">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${esc(title)}">`,
    `<meta name="twitter:description" content="${esc(description)}">`,
    `<meta name="twitter:image" content="${OG_IMG}">`,
    ...jsonLdArray.map((s) => `<script type="application/ld+json">${JSON.stringify(s)}</script>`),
  ]
    .filter(Boolean)
    .join("\n    ");
}

function getMetaForRoute(route, html) {
  if (STATIC_META[route]) {
    return { ...STATIC_META[route], canonical: `${BASE}${route === "/" ? "" : route}` };
  }

  // Blog post: parse title and excerpt from rendered HTML
  if (route.startsWith("/blog/")) {
    const slug = route.replace("/blog/", "");
    // Title: plain <h1> inside blogpost-header (no class attribute)
    const titleMatch = html.match(/class="blogpost-header[\s\S]*?<h1>([^<]+)<\/h1>/i);
    const title = titleMatch ? titleMatch[1].trim() : slug;
    // Excerpt: first <p class="blogpost-p"> paragraph
    const excerptMatch = html.match(/<p class="blogpost-p">([^<]{40,})</i);
    const description = excerptMatch
      ? excerptMatch[1].trim().replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&lt;/g, "<").replace(/&gt;/g, ">").slice(0, 160)
      : `Read ${title} on the That Works blog.`;
    // Date: from blog-meta div
    const dateMatch = html.match(/(\d{4}-\d{2}-\d{2})/);
    const datePublished = dateMatch ? dateMatch[1] : new Date().toISOString().split("T")[0];
    return {
      title: `${title} — That Works`,
      description,
      canonical: `${BASE}${route}`,
      jsonLd: [
        {
          "@context": "https://schema.org",
          "@type": "BlogPosting",
          headline: title,
          description,
          author: { "@type": "Organization", name: "That Works" },
          publisher: { "@type": "Organization", name: "That Works", logo: { "@type": "ImageObject", url: OG_IMG } },
          datePublished,
          url: `${BASE}${route}`,
        },
        {
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          itemListElement: [
            { "@type": "ListItem", position: 1, name: "Home", item: BASE },
            { "@type": "ListItem", position: 2, name: "Blog", item: `${BASE}/blog` },
            { "@type": "ListItem", position: 3, name: title, item: `${BASE}${route}` },
          ],
        },
      ],
    };
  }

  return null;
}

/** Convert dist file path to route */
function filePathToRoute(filePath) {
  const rel = relative(DIST, filePath).replace(/\.html$/, "").replace(/\\/g, "/");
  if (rel === "index") return "/";
  return `/${rel}`;
}

/** Recursively find all .html files */
function findHtmlFiles(dir) {
  const results = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...findHtmlFiles(full));
    } else if (entry.endsWith(".html")) {
      results.push(full);
    }
  }
  return results;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

const htmlFiles = findHtmlFiles(DIST);
let injected = 0;
let skipped = 0;

for (const filePath of htmlFiles) {
  const html = readFileSync(filePath, "utf-8");
  const route = filePathToRoute(filePath);
  const meta = getMetaForRoute(route, html);

  if (!meta) {
    skipped++;
    continue;
  }

  // Skip if meta already injected (idempotent)
  if (html.includes("<title>")) {
    // Remove existing title if present (from a previous run)
  }

  const tags = buildHeadTags(meta);
  const updated = html.replace("</head>", `    ${tags}\n  </head>`);

  writeFileSync(filePath, updated);
  injected++;
}

console.log(`[inject-meta] Injected meta into ${injected} pages (${skipped} skipped).`);
